using AutoMapper;
using Proj1.DTOs;
using Proj1.Models.Entities;
using Proj1.Models.ViewModels;

namespace Proj1.MappingProfiles;

/// <summary>
/// AutoMapper profile for resident mappings.
/// Defines how to convert between entities, DTOs, and view models.
/// Best Practice: Keep all resident-related mappings in one profile.
/// </summary>
public class ResidentProfile : Profile
{
    public ResidentProfile()
    {
        // ========================================
        // ENTITY → DTO MAPPINGS
        // ========================================

        /// <summary>
        /// Maps Resident entity to DTO.
        /// Simple mapping - all properties match by name.
        /// </summary>
        CreateMap<Resident, ResidentDto>();

        // ========================================
        // DTO → ENTITY MAPPINGS (CREATE)
        // ========================================

        /// <summary>
        /// Maps create DTO to new Resident entity.
        /// 
        /// LEARNING: When creating a new resident:
        /// 1. Id is auto-generated by the database
        /// 2. UserId is set in the service layer after creating the Identity user
        /// 3. Audit fields (CreatedDate, CreatedBy, etc.) are set by the repository
        /// 
        /// We must ignore all these properties to avoid AutoMapper errors.
        /// </summary>
        CreateMap<CreateResidentDto, Resident>()
            // ✅ FIX: Ignore auto-generated properties
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            
            // ✅ FIX: Ignore UserId - it's set after creating the Identity user
            .ForMember(dest => dest.UserId, opt => opt.Ignore())
            
            // ✅ FIX: Ignore navigation properties
            .ForMember(dest => dest.ClearanceRequests, opt => opt.Ignore())
            
            // ✅ FIX: Ignore computed properties
            .ForMember(dest => dest.FullName, opt => opt.Ignore())
            
            // ✅ FIX: Ignore audit/base entity properties (set by repository)
            .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedDate, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
            .ForMember(dest => dest.DeletedDate, opt => opt.Ignore());

        // ========================================
        // DTO → ENTITY MAPPINGS (UPDATE)
        // ========================================

        /// <summary>
        /// Maps update DTO to existing Resident entity.
        /// 
        /// LEARNING: When updating a resident:
        /// 1. UserId should NOT change (it's tied to the Identity user)
        /// 2. Audit fields are updated by the repository, not from the DTO
        /// 
        /// We ignore these properties because they shouldn't be modified during update.
        /// </summary>
        CreateMap<UpdateResidentDto, Resident>()
            // ✅ FIX: Ignore UserId - it should never change after creation
            .ForMember(dest => dest.UserId, opt => opt.Ignore())
            
            // ✅ FIX: Ignore navigation properties
            .ForMember(dest => dest.ClearanceRequests, opt => opt.Ignore())
            
            // ✅ FIX: Ignore computed properties
            .ForMember(dest => dest.FullName, opt => opt.Ignore())
            
            // ✅ FIX: Ignore audit/base entity properties (updated by repository)
            .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedDate, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
            .ForMember(dest => dest.DeletedDate, opt => opt.Ignore());

        // ========================================
        // DTO → VIEW MODEL MAPPINGS
        // ========================================

        /// <summary>
        /// Maps DTO to list view model with computed FullName property.
        /// ✅ Simple concatenation without MiddleName
        /// </summary>
        CreateMap<ResidentDto, ResidentViewModel>()
            .ForMember(dest => dest.FullName,
                opt => opt.MapFrom(src => $"{src.FirstName} {src.LastName}"));

        /// <summary>
        /// Maps DTO to edit view model.
        /// Simple mapping - properties match by name.
        /// </summary>
        CreateMap<ResidentDto, EditResidentViewModel>();

        /// <summary>
        /// Maps DTO to details view model with computed FullName property.
        /// ✅ Simple concatenation without MiddleName
        /// </summary>
        CreateMap<ResidentDto, ResidentDetailsViewModel>()
            .ForMember(dest => dest.FullName,
                opt => opt.MapFrom(src => $"{src.FirstName} {src.LastName}"));

        // ========================================
        // VIEW MODEL → DTO MAPPINGS
        // ========================================

        /// <summary>
        /// Maps edit view model to update DTO.
        /// Simple mapping - properties match by name.
        /// </summary>
        CreateMap<EditResidentViewModel, UpdateResidentDto>();

        /// <summary>
        /// Maps create view model to create DTO.
        /// Simple mapping - properties match by name.
        /// </summary>
        CreateMap<CreateResidentViewModel, CreateResidentDto>();
    }
}